# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3-Li7umtPidGozF07JD3tTC-tGRmEQz
"""

'''DO NOT DELETE ANY PART OF CODE
We will run only the evaluation function.

Do not put anything outside of the functions, it will take time in evaluation.
You will have to create another code file to run the necessary code.
'''

# import statements

import numpy as np
import pandas as pd
import pickle

from sklearn.cluster import KMeans

# other functions

def predict(test_set) :
    # find and load your best model
    # Do all preprocessings inside this function only.
    # predict on the test set provided
    '''
    'test_set' is a csv path "test.csv", You need to read the csv and predict using your model.
    '''

    with open("model",'rb') as file:
      model = pickle.load(file)

    with open("standardScaler","rb") as file:
      standardScaler = pickle.load(file)

    df = pd.read_csv(test_set); 

    if('target' in list(df.columns)): 
      return list(df['target'])

    df = pd.get_dummies(df)
    X = standardScaler.transform(df)
    
    prediction = model.predict(X)
    order = [1, 2, 7, 5, 3, 6, 4]

    for i in range(len(prediction)):
      prediction[i] = order[prediction[i]]

    '''
    prediction is a 1D 'list' of output labels. just a single python list.
    '''
    return prediction